---
title: "Publications"
---
<style type="text/css">
h1.title {
  font-size: 52px;
  text-align: center;
}
body {
background-color: #B9F2FE
}
</style>
<br>
*Links to publications are provided. If you cannot freely access a publication DO NOT PAY. Instead, please email Stephanie at sarcher at lumcon.edu and she will send you a copy.*  
<br>  
Archer, SK, AS Kahn, M Thiess, L Law, SP Leys, SC Johannessen, CA Layman, L Burke, and A Dunham.	2020. Foundation Species Abundance Influences Food Web Topology on Glass Sponge Reefs. Frontiers in	Marine Science 7:549478. DOI: 10.3389/fmars.2020.549478<br>    
<br>
Archer, SK, G Dennison, L Tryon, S Byers, and A Dunham. 2020. Invertebrate settlement and diversity	on a glass sponge reef. The Canadian Field-Naturalist 134:1. DOI: 10.22621/cfn.v134i1.2297<br>    
<br>
Stevenson, A, SK Archer, JA Schultz, A Dunham, JB Marliave, P Martone, and CDG Harley. 2020	Warming and acidification threaten ancient glass sponge filtration and reef formation. Scientific Reports	10:8176. DOI: 10.1038/s41598-020-65220-9<br>    
<br>
Rossi, RE, SK Archer, C Giri, and CA Layman. 2020. The role of multiple stressors in a dwarf red	mangrove (Rhizophora mangle) die-off. Estuarine, Coastal, and Shelf Science. 237:106660. DOI:	10.1016/j.ecss.2020.106660<br>    
<br>
Guillas, KC*, AS Kahn, N Grant, SK Archer, A Dunham, and SP Leys. 2019. Settlement of juvenile glass	sponges and other invertebrate cryptofauna on the Hecate Strait glass sponge reefs. Invertebrate Biology.	e12266. DOI: 10.1111/ivb.12266<br>    
<br>
Loh, TL, SK Archer, and A Dunham. 2019. Monitoring program design for data‐limited marine biogenic	habitats: A structured approach. Ecology and Evolution. 9:7346-7359. DOI:10.1002/ece3.5261<br>    
<br>
Grant, N., E. Matveev, A. S. Kahn, S. K. Archer, A. Dunham, R. J. Bannister, D. Eerkes-Medrano, and S. P.	Leys. 2019. Effect of suspended sediments on the pumping rates of three species of glass sponge in situ.	Marine Ecology Progress Series 615:79-100. DOI: 10.3354/meps12939<br>    
<br>
Dunham, A, SK Archer, SC Davies, LA Burke, J Mossman, JR Pegg, and E Archer. 2018. Assessing	condition and ecological role of deep-water biogenic habitats: Glass sponge reefs in the Salish Sea. Marine	Environmental Research. 141:88-99. DOI:10.1016/j.marenvres.2018.08.002<br>    
<br>
Archer, SK, WD Halliday, A Riera, X. Mouy, JWF Chu, MK Pine, A Dunham, and F Juanes. 2018.	The first description of a glass sponge reef soundscape reveals fish calls and elevated sound pressure levels. 	Marine Ecology Progress Series. 595:245-252 DOI:10.3354/meps12572<br>    
<br>
Archer, SK, S Buhler, and CA Layman. 2018. Ambient nutrient availability drives the outcome of an	interaction between a sponge (Halichondria melanadocia) and a seagrass (Thalassia testudinum). Journal of	Experimental Marine Biology and Ecology 503:86-91 DOI: 10.1016/j.jembe.2018.02.005<br>    
<br>
Archer, SK, AS Kahn, SP Leys, T Norgard, F Girard, CP Du Preez, and A Dunham. 2018. Pyrosome	consumption by benthic organisms during blooms in the NE Pacific and Gulf of Mexico. Ecology 99:981	984. DOI: 10.1002/ecy.2097<br>    
<br>
Archer, SK, JL Stevens, RE Rossi, KO Matterson, and CA Layman. 2017. Abiotic conditions drive significant variability in microbial activity and nutrient processing in a common Caribbean sponge, Ircinia	felix. Limnology and Oceanography 62: 1783–1793. DOI:10.1002/lno.10533<br>    
<br>
Easson, CG, SK Archer, KO Matterson, CJ Freeman, and RW Thacker. 2015. Spatial variability in sponge	community assemblages across an anthropogenic gradient in Bocas Del Toro, Panama. PeerJ 3:e1385<br>    
<br>
Layman, CA, S Buhler, ST Giery, R Rossi, T Penland, M Henson, A Bogdanoff, M Cove, A Irizarry, C Schalke, and SK Archer. 2015. A primer on the history of food web ecology: Fundamental contributions		of fourteen researchers. Food Webs 4: 14-24<br>    
<br>
Archer, SK, EW Stoner, and CA Layman. 2015. A complex interaction between a sponge (Halichondria		melanadocia) and a seagrass (Thalassia testudinum) in a subtropical coastal ecosystem. Journal of			Experimental Marine Biology and Ecology 465:33-40<br>    
<br>
Archer, SK, JE Allgeier, BX Semmens, SA Heppell, CV Pattengill-Semmens, AD Rosemond, PG Bush, CM		McCoy, BC Johnson, and CA Layman. 2015. Hot moments in spawning aggregations: Implications for		ecosystem-scale nutrient cycling. Coral Reefs 34(1):19-23. DOI: 10.1007/s00338-014-1208-4<br>    
<br>
Archer, SK and TA Crowl. 2014. Retention of learned predator recognition in an endangered sucker			Chasmistes liorus liorus. Aquatic Biology 20:195-202. DOI: 10.3354/ab00558<br>    
<br>
Layman CA, ZR Jud, SK Archer, and D Riera*. 2014. Provision of ecosystem services by artificial shoreline		structures in a highly impacted estuary. Environmental Research Letters 9: 044009. DOI: 10.1088/1748		9326/9/4/044009<br>    
<br>
Heppell, SA, BX Semmens, SK Archer, CV Pattengill-Semmens, PG Bush, BC Johnson, CM McCoy, and SS		Heppell. 2012.  Documenting recovery of a spawning aggregation through size frequency analysis from		underwater laser calipers measurements. Biological Conservation 155: 119-127<br>    
<br>
Archer, SK, SA Heppell, BX Semmens, CV Pattengill-Semmens, PG Bush, CM McCoy, and BC Johnson.		2012. Patterns of color phase indicate spawn timing at a Nassau grouper (Epinephelus striatus) spawning		aggregation. Current Zoology 58(1):70-80
